### ISSUE TITLE
name 'DeCap' is not defined

### ISSUE THREAD

**Issue by nidongpinyinme** [Artanic30/MacCap#5]
thanks for your wonderful work, but when i try to reproduce this work, I facing up this issue in [here](https://github.com/Artanic30/MacCap/blob/main/models/models/MacCap.py#L145), is there a mistake?

**Comment by Artanic30** [comment]
Sorry for the mistake. I update the code, the bug should be fixed.

**Comment by nidongpinyinme** [comment]
sorry to bother you again
but when I use the updated code to start train, it still have some problem, like [BaseModel](https://github.com/Artanic30/MacCap/blob/main/models/BaseModel.py#L63) which need a decap_cc3m.pth and [main](https://github.com/Artanic30/MacCap/blob/main/main.py#L161) where face an error "ValueError: If inputs_embeds is passed as model-specific keyword input then model has to be an encoder-decoder and not a OPTForCausalLM."
Since I'm not using a distributed set, could you please have a check on this?

**Comment by nidongpinyinme** [comment]
sorry, it's my fault, I was in a wrong environment.
